spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_disco?useSSL=false
    username: root
    password: 1234
    platform: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

